USE dh199;

DROP TABLE IF EXISTS milken;

CREATE TABLE milken (
    volume INT,
    composer VARCHAR(150),
    title VARCHAR(150) NOT NULL,
    minutesDuration DECIMAL(4,2),
    yearKnown int,
    yearEstimated VARCHAR(50),
    commissioned VARCHAR(1),
    commissioningInstitutionName VARCHAR(250),
    commissioningInstitutionType VARCHAR(100),
    primaryGenre VARCHAR(20),
    instrumentation VARCHAR(50),
    formGeneral VARCHAR(50),
    formSpecific_or_tertiaryGenre VARCHAR(50),
    other VARCHAR(50),
    sacred VARCHAR(1),
    secular VARCHAR(1),
    ashkenazi VARCHAR(1),
    sephardi VARCHAR(1),
    israeli VARCHAR(1),
    mizrahi VARCHAR(1),
    musical VARCHAR(1),
    conceptual VARCHAR(1),
    textual VARCHAR(1),
    functional VARCHAR(1),
    sonic VARCHAR(1),
    social VARCHAR(1),
    classical VARCHAR(1),
    klezmer VARCHAR(1),
    cantorial VARCHAR(1),
    folk VARCHAR(1),
    jazz VARCHAR(1),
    devotionalSolemn VARCHAR(1),
    popular VARCHAR(1),
    theatrical VARCHAR(1),
    text VARCHAR(1),
    textType VARCHAR(50),
    textSource VARCHAR(150),
    hebrew VARCHAR(1),
    yiddish VARCHAR(1),
    english VARCHAR(1),
    ladino VARCHAR(1),
    german VARCHAR(1),
    otherLanguages VARCHAR(1),
    notes1 VARCHAR(1000),
    notes2 VARCHAR(1000),
    notes3 VARCHAR(1000),
    PRIMARY KEY(title)
);
